apiVersion: v1
kind: Service
metadata:
  name: kyc
  namespace: lendkit
  labels:
    app: kyc
    app.kubernetes.io/name: kyc
    app.kubernetes.io/part-of: lendkit
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: kyc
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8001
      protocol: TCP
