-- LendKit PostgreSQL initialization
CREATE DATABASE credit;
CREATE DATABASE loans;
CREATE DATABASE repayment;

GRANT ALL PRIVILEGES ON DATABASE credit TO lendkit;
GRANT ALL PRIVILEGES ON DATABASE loans TO lendkit;
GRANT ALL PRIVILEGES ON DATABASE repayment TO lendkit;

\c kyc
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

\c credit
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

\c loans
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

\c repayment
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
